name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore  BDataGrid.Library/BDataGrid.Library.csproj
    - name: Build
      run: dotnet build  BDataGrid.Library/BDataGrid.Library.csproj --configuration Release --no-restore
